version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  web:
    build: ./Docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf